var gl,osg={copyright:"Cedric Pinson - cedric.pinson@plopbyte.net",instance:0,version:0,log:function(a){},reportErrorGL:!1,init:function(){void 0===Float32Array.set&&(Float32Array.prototype.set=function(a){for(var b=0,c=a.length;b<c;++b)this[b]=a[b]});void 0===Int32Array.set&&(Int32Array.prototype.set=function(a){for(var b=0,c=a.length;b<c;++b)this[b]=a[b]})},checkError:function(a){0!==a&&(1280===a?osg.log("detected error INVALID_ENUM"):1281===a?osg.log("detected error INVALID_VALUE"):1282===a?osg.log("detected error INVALID_OPERATION"):
1285===a?osg.log("detected error OUT_OF_MEMORY"):1286===a?osg.log("detected error INVALID_FRAMEBUFFER_OPERATION"):osg.log("detected error UNKNOWN"))},initGL:function(a){try{gl=a.getContext("experimental-webgl",{antialias:!0}),osg.init()}catch(b){}gl||alert("Could not initialise WebGL, sorry :-(")},objectInehrit:function(a,b){function c(){}c.prototype=a;c.prototype.superObject=a;var d=new c;b&&osg.objectMix(d,b,!1);return d},objectMix:function(a,b,c){for(var d in b)c&&a[d]||(a[d]=b[d]);return a},Matrix:{setRow:function(a,
b,c,d,e,f){b*=4;a[b+0]=c;a[b+1]=d;a[b+2]=e;a[b+3]=f},innerProduct:function(a,b,c,d){c*=4;return a[c+0]*b[0+d]+a[c+1]*b[4+d]+a[c+2]*b[8+d]+a[c+3]*b[12+d]},set:function(a,b,c,d){return a[4*b+c]=d},get:function(a,b,c){return a[4*b+c]},makeIdentity:function(a){void 0===a&&(a=[]);osg.Matrix.setRow(a,0,1,0,0,0);osg.Matrix.setRow(a,1,0,1,0,0);osg.Matrix.setRow(a,2,0,0,1,0);osg.Matrix.setRow(a,3,0,0,0,1);return a},makeTranslate:function(a,b,c,d){void 0===d&&(d=[]);osg.Matrix.setRow(d,0,1,0,0,0);osg.Matrix.setRow(d,
1,0,1,0,0);osg.Matrix.setRow(d,2,0,0,1,0);osg.Matrix.setRow(d,3,a,b,c,1);return d},setTrans:function(a,b,c,d){a[12]=b;a[13]=c;a[14]=d;return a},getTrans:function(a,b){void 0===b&&(b=[]);b[0]=a[12];b[1]=a[13];b[2]=a[14];return b},preMult:function(a,b){for(var c=[],d=0;4>d;d++)c[0]=osg.Matrix.innerProduct(b,a,0,d),c[1]=osg.Matrix.innerProduct(b,a,1,d),c[2]=osg.Matrix.innerProduct(b,a,2,d),c[3]=osg.Matrix.innerProduct(b,a,3,d),a[0+d]=c[0],a[4+d]=c[1],a[8+d]=c[2],a[12+d]=c[3];return a},postMult:function(a,
b){for(var c=[],d=0;4>d;d++)c[0]=osg.Matrix.innerProduct(a,b,d,0),c[1]=osg.Matrix.innerProduct(a,b,d,1),c[2]=osg.Matrix.innerProduct(a,b,d,2),c[3]=osg.Matrix.innerProduct(a,b,d,3),this.setRow(a,d,c[0],c[1],c[2],c[3]);return a},mult:function(a,b,c){if(c===a)return this.postMult(c,b);if(c===b)return this.preMult(c,a);void 0===c&&(c=[]);var d=a[0],e=a[1],f=a[2],g=a[3],h=a[4],k=a[5],m=a[6],p=a[7],n=a[8],q=a[9],u=a[10],r=a[11],x=a[12],v=a[13],y=a[14];a=a[15];var w=b[0],z=b[1],A=b[2],B=b[3],C=b[4],D=b[5],
E=b[6],F=b[7],G=b[8],H=b[9],I=b[10],J=b[11],t=b[12],K=b[13],L=b[14];b=b[15];c[0]=d*w+e*C+f*G+g*t;c[1]=d*z+e*D+f*H+g*K;c[2]=d*A+e*E+f*I+g*L;c[3]=d*B+e*F+f*J+g*b;c[4]=h*w+k*C+m*G+p*t;c[5]=h*z+k*D+m*H+p*K;c[6]=h*A+k*E+m*I+p*L;c[7]=h*B+k*F+m*J+p*b;c[8]=n*w+q*C+u*G+r*t;c[9]=n*z+q*D+u*H+r*K;c[10]=n*A+q*E+u*I+r*L;c[11]=n*B+q*F+u*J+r*b;c[12]=x*w+v*C+y*G+a*t;c[13]=x*z+v*D+y*H+a*K;c[14]=x*A+v*E+y*I+a*L;c[15]=x*B+v*F+y*J+a*b;return c},preMultVec3:function(a,b,c){void 0===c&&(c=[]);var d=1/(a[3]*b[0]+a[7]*b[1]+
a[11]*b[2]+a[15]);c[0]=(a[0]*b[0]+a[4]*b[1]+a[8]*b[2]+a[12])*d;c[1]=(a[1]*b[0]+a[5]*b[1]+a[9]*b[2]+a[13])*d;c[2]=(a[2]*b[0]+a[6]*b[1]+a[10]*b[2]+a[14])*d;return c},postMultVec3:function(a,b,c){void 0===c&&(c=[]);var d=1/(a[12]*b[0]+a[13]*b[1]+a[14]*b[2]+a[15]);c[0]=(a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3])*d;c[1]=(a[4]*b[0]+a[5]*b[1]+a[6]*b[2]+a[7])*d;c[2]=(a[8]*b[0]+a[9]*b[1]+a[10]*b[2]+a[11])*d;return c},makeLookAt:function(a,b,c,d){void 0===d&&(d=[]);b=osg.Vec3.sub(b,a);osg.Vec3.normalize(b,b);c=osg.Vec3.cross(b,
c);osg.Vec3.normalize(c,c);var e=osg.Vec3.cross(c,b);osg.Vec3.normalize(e,e);d[0]=c[0];d[1]=e[0];d[2]=-b[0];d[3]=0;d[4]=c[1];d[5]=e[1];d[6]=-b[1];d[7]=0;d[8]=c[2];d[9]=e[2];d[10]=-b[2];d[11]=0;d[12]=0;d[13]=0;d[14]=0;d[15]=1;osg.Matrix.preMultTranslate(d,osg.Vec3.neg(a),d);return d},makeOrtho:function(a,b,c,d,e,f,g){void 0===g&&(g=[]);var h=-(b+a)/(b-a),k=-(d+c)/(d-c),m=-(f+e)/(f-e),p=osg.Matrix.setRow;p(g,0,2/(b-a),0,0,0);p(g,1,0,2/(d-c),0,0);p(g,2,0,0,-2/(f-e),0);p(g,3,h,k,m,1);return g},getLookAt:function(a,
b,c,d,e){void 0===e&&(e=1);var f=osg.Matrix.inverse(a);osg.Matrix.preMultVec3(f,[0,0,0],b);osg.Matrix.transform3x3(a,[0,1,0],d);osg.Matrix.transform3x3(a,[0,0,-1],c);osg.Vec3.normalize(c,c);osg.Vec3.add(osg.Vec3.mult(c,e),b,c)},getRotate:function(a,b){void 0===b&&(b=[]);var c;c=[];var d,e;d=a[0];e=a[5];var f=a[10];c[0]=1+d+e+f;c[1]=1+d-e-f;c[2]=1-d+e-f;c[3]=1-d-e+f;e=0;for(d=1;4>d;d++)c[d]>c[e]&&(e=d);0===e?(b[3]=c[0],b[0]=a[6]-a[9],b[1]=a[8]-a[2],b[2]=a[1]-a[4]):1==e?(b[3]=a[6]-a[9],b[0]=c[1],b[1]=
a[1]+a[4],b[2]=a[8]+a[2]):2==e?(b[3]=a[8]-a[2],b[0]=a[1]+a[4],b[1]=c[2],b[2]=a[6]+a[9]):(b[3]=a[1]-a[4],b[0]=a[8]+a[2],b[1]=a[6]+a[9],b[2]=c[3]);c=Math.sqrt(.25/c[e]);b[3]*=c;b[0]*=c;b[1]*=c;b[2]*=c;return b},preMultTranslate:function(a,b,c){void 0===c&&(c=[]);c!==a&&osg.Matrix.copy(a,c);var d;0!==b[0]&&(d=b[0],c[12]+=d*a[0],c[13]+=d*a[1],c[14]+=d*a[2],c[15]+=d*a[3]);0!==b[1]&&(d=b[1],c[12]+=d*a[4],c[13]+=d*a[5],c[14]+=d*a[6],c[15]+=d*a[7]);0!==b[2]&&(d=b[2],c[12]+=d*a[8],c[13]+=d*a[9],c[14]+=d*a[10],
c[15]+=d*a[11]);return c},makeRotate:function(a,b,c,d,e){void 0===e&&(e=[]);var f=Math.sqrt(b*b+c*c+d*d),g=Math.sin(a);a=Math.cos(a);if(0<f){var h,k,m,p,n,f=1/f;b*=f;c*=f;d*=f;f=b*c;h=c*d;k=d*b;m=b*g;p=c*g;g*=d;n=1-a;e[0]=n*b*b+a;e[1]=n*f-g;e[2]=n*k+p;e[3]=0;e[4]=n*f+g;e[5]=n*c*c+a;e[6]=n*h-m;e[7]=0;e[8]=n*k-p;e[9]=n*h+m;e[10]=n*d*d+a;e[11]=0;e[12]=0;e[13]=0;e[14]=0;e[15]=1}return e},transform3x3:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]*b[0]+a[1]*b[1]+a[2]*b[2];c[1]=a[4]*b[0]+a[5]*b[1]+a[6]*b[2];
c[2]=a[8]*b[0]+a[9]*b[1]+a[10]*b[2];return c},transformVec3:function(a,b,c){var d=1/(b[3]*a[0]+b[7]*a[1]*b[11]*a[2]+b[15]);void 0===c&&(c=[]);var e;e=c===a?[]:c;e[0]=(b[0]*a[0]+b[4]*a[1]+b[8]*a[2]+b[12])*d;e[1]=(b[1]*a[0]+b[5]*a[1]+b[9]*a[2]+b[13])*d;e[2]=(b[2]*a[0]+b[6]*a[1]+b[10]*a[2]+b[14])*d;c===a&&osg.Vec3.copy(e,c);return c},transformVec4:function(a,b,c){void 0===c&&(c=[]);var d;d=c===a?[]:c;d[0]=b[0]*a[0]+b[1]*a[1]+b[2]*a[2]+b[3]*a[3];d[1]=b[4]*a[0]+b[5]*a[1]+b[6]*a[2]+b[7]*a[3];d[2]=b[8]*
a[0]+b[9]*a[1]+b[10]*a[2]+b[11]*a[3];d[3]=b[12]*a[0]+b[13]*a[1]+b[14]*a[2]+b[15]*a[3];c===a&&osg.Vec4.copy(d,c);return c},copy:function(a,b){void 0===b&&(b=[]);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},inverse:function(a,b){return this.inverse4x4(a,b)},inverse4x4:function(a,b){result=void 0===b?[]:b;var c=a[10]*a[15],d=a[14]*a[11],e=a[6]*a[15],f=a[14]*a[7],g=
a[6]*a[11],h=a[10]*a[7],k=a[2]*a[15],m=a[14]*a[3],p=a[2]*a[11],n=a[10]*a[3],q=a[2]*a[7],u=a[6]*a[3],r=a[8]*a[13],x=a[12]*a[9],v=a[4]*a[13],y=a[12]*a[5],w=a[4]*a[9],z=a[8]*a[5],A=a[0]*a[13],B=a[12]*a[1],C=a[0]*a[9],D=a[8]*a[1],E=a[0]*a[5],F=a[4]*a[1],G=c*a[5]+f*a[9]+g*a[13]-(d*a[5]+e*a[9]+h*a[13]),H=d*a[1]+k*a[9]+n*a[13]-(c*a[1]+m*a[9]+p*a[13]),I=e*a[1]+m*a[5]+q*a[13]-(f*a[1]+k*a[5]+u*a[13]),J=h*a[1]+p*a[5]+u*a[9]-(g*a[1]+n*a[5]+q*a[9]),t=a[0]*G+a[4]*H+a[8]*I+a[12]*J;if(1E-5>Math.abs(t)){osg.log("Warning can't inverse matrix "+
a);if(void 0!==b)return!1;osg.Matrix.makeIdentity(result)}var t=1/t,K=t*(d*a[4]+e*a[8]+h*a[12]-(c*a[4]+f*a[8]+g*a[12])),c=t*(c*a[0]+m*a[8]+p*a[12]-(d*a[0]+k*a[8]+n*a[12])),e=t*(f*a[0]+k*a[4]+u*a[12]-(e*a[0]+m*a[4]+q*a[12])),g=t*(g*a[0]+n*a[4]+q*a[8]-(h*a[0]+p*a[4]+u*a[8])),h=t*(r*a[7]+y*a[11]+w*a[15]-(x*a[7]+v*a[11]+z*a[15])),p=t*(x*a[3]+A*a[11]+D*a[15]-(r*a[3]+B*a[11]+C*a[15])),n=t*(v*a[3]+B*a[7]+E*a[15]-(y*a[3]+A*a[7]+F*a[15])),q=t*(z*a[3]+C*a[7]+F*a[11]-(w*a[3]+D*a[7]+E*a[11])),u=t*(v*a[10]+z*
a[14]+x*a[6]-(w*a[14]+r*a[6]+y*a[10])),r=t*(C*a[14]+r*a[2]+B*a[10]-(A*a[10]+D*a[14]+x*a[2])),v=t*(A*a[6]+F*a[14]+y*a[2]-(E*a[14]+v*a[2]+B*a[6])),w=t*(E*a[10]+w*a[2]+D*a[6]-(C*a[6]+F*a[10]+z*a[2]));result[0]=t*G;result[1]=t*H;result[2]=t*I;result[3]=t*J;result[4]=K;result[5]=c;result[6]=e;result[7]=g;result[8]=h;result[9]=p;result[10]=n;result[11]=q;result[12]=u;result[13]=r;result[14]=v;result[15]=w;return void 0!==b?!0:result},inverse4x3:function(a,b){result=void 0===b?[]:b;result[0]=a[5]*a[10]-
a[6]*a[9];result[1]=a[2]*a[9]-a[1]*a[10];result[2]=a[1]*a[6]-a[2]*a[5];var c=a[0],d=a[4],e=a[8],f=1/(c*result[0]+d*result[1]+e*result[2]),c=c*f,d=d*f,e=e*f;result[0]*=f;result[1]*=f;result[2]*=f;result[3]=0;result[4]=a[6]*e-d*a[10];result[5]=c*a[10]-a[2]*e;result[6]=a[2]*d-c*a[6];result[7]=0;result[8]=d*a[9]-a[5]*e;result[9]=a[1]*e-c*a[9];result[10]=c*a[5]-a[1]*d;result[11]=0;result[15]=1;var c=a[15],d=c-1,g,h,k;if(1E-6<d*d){d=[];result[12]=result[13]=result[15]=0;g=a[3];h=a[7];k=a[11];var e=result[0]*
g+result[1]*h+result[2]*k,f=result[4]*g+result[5]*h+result[6]*k,m=result[8]*g+result[9]*h+result[10]*k;g=a[12];h=a[13];k=a[14];c=1/(c-(g*e+h*f+k*m));g*=c;h*=c;k*=c;d[0]=g*e+1;d[1]=h*e;d[2]=k*e;d[3]=-e*c;d[4]=g*f;d[5]=h*f+1;d[6]=k*f;d[7]=-f*c;d[8]=g*m;d[9]=h*m;d[10]=k*m+1;d[11]=-m*c;d[12]=-g;d[13]=-h;d[14]=-k;d[15]=c;this.preMult(result,d)}else g=a[12],h=a[13],k=a[14],result[12]=-(g*result[0]+h*result[4]+k*result[8]),result[13]=-(g*result[1]+h*result[5]+k*result[9]),result[14]=-(g*result[2]+h*result[6]+
k*result[10]);return void 0!==b?!0:result},transpose:function(a,b){void 0===b&&(b=[]);var c;c=b===a?osg.Matrix.copy(a,b):b;b!==a&&(c[0]=a[0],c[5]=a[5],c[10]=a[10],c[15]=a[15]);c[1]=a[4];c[2]=a[8];c[3]=a[12];c[4]=a[1];c[6]=a[9];c[7]=a[13];c[8]=a[2];c[9]=a[5];c[11]=a[14];c[12]=a[3];c[13]=a[7];c[14]=a[11];b===a&&osg.Matrix.copy(c,b);return b},makePerspective:function(a,b,c,d,e){void 0===e&&(e=[]);a=c*Math.tan(a*Math.PI/360);var f=-a;return osg.Matrix.makeFrustum(f*b,a*b,f,a,c,d,e)},makeScale:function(a,
b,c,d){void 0===d&&(d=[]);this.setRow(d,0,a,0,0,0);this.setRow(d,1,0,b,0,0);this.setRow(d,2,0,0,c,0);this.setRow(d,3,0,0,0,1);return d},makeFrustum:function(a,b,c,d,e,f,g){void 0===g&&(g=[]);var h=2*e/(d-c),k=(b+a)/(b-a);c=(d+c)/(d-c);d=-(f+e)/(f-e);f=-2*f*e/(f-e);this.setRow(g,0,2*e/(b-a),0,0,0);this.setRow(g,1,0,h,0,0);this.setRow(g,2,k,c,d,-1);this.setRow(g,3,0,0,f,0);return g},makeRotateFromQuat:function(a,b){void 0===b&&(b=[]);this.makeIdentity(b);return this.setRotateFromQuat(b,a)},setRotateFromQuat:function(a,
b){var c=osg.Quat.length2(b);if(Math.abs(c)<=Number.MIN_VALUE)a[0]=0,a[1]=0,a[2]=0,a[4]=0,a[5]=0,a[6]=0,a[8]=0,a[9]=0,a[10]=0;else{var c=1!==c?2/c:2,d,e,f,g,h,k,m,p;d=c*b[0];e=c*b[1];f=c*b[2];c=b[0]*d;k=b[0]*e;m=b[0]*f;g=b[1]*e;h=b[1]*f;p=b[2]*f;d*=b[3];e*=b[3];f*=b[3];a[0]=1-(g+p);a[4]=k-f;a[8]=m+e;a[1]=k+f;a[5]=1-(c+p);a[9]=h-d;a[2]=m-e;a[6]=h+d;a[10]=1-(c+g)}return a}},Vec2:{copy:function(a,b){void 0===b&&(b=[]);b[0]=a[0];b[1]=a[1];return b},valid:function(a){return isNaN(a[0])||isNaN(a[1])?!1:
!0},mult:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]*b;c[1]=a[1]*b;return c},length2:function(a){return a[0]*a[0]+a[1]*a[1]},length:function(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1])},normalize:function(a,b){void 0===b&&(b=a);var c=this.length2(a);0<c&&(c=1/Math.sqrt(c),b[0]=a[0]*c,b[1]=a[1]*c);return b},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]},sub:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]-b[0];c[1]=a[1]-b[1];return c},add:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]+b[0];c[1]=a[1]+b[1];return c},
neg:function(a,b){void 0===b&&(b=[]);b[0]=-a[0];b[1]=-a[1];return b},lerp:function(a,b,c,d){void 0===d&&(d=[]);var e=1-a;d[0]=b[0]*e+a*c[0];d[1]=b[1]*e+a*c[1];return d}},Vec3:{copy:function(a,b){void 0===b&&(b=[]);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},cross:function(a,b,c){void 0===c&&(c=[]);c[0]=a[1]*b[2]-a[2]*b[1];c[1]=a[2]*b[0]-a[0]*b[2];c[2]=a[0]*b[1]-a[1]*b[0];return c},valid:function(a){return isNaN(a[0])||isNaN(a[1])||isNaN(a[2])?!1:!0},mult:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]*b;
c[1]=a[1]*b;c[2]=a[2]*b;return c},length2:function(a){return a[0]*a[0]+a[1]*a[1]+a[2]*a[2]},length:function(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])},normalize:function(a,b){void 0===b&&(b=a);var c=this.length2(a);0<c&&(c=1/Math.sqrt(c),b[0]=a[0]*c,b[1]=a[1]*c,b[2]=a[2]*c);return b},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},sub:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},add:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]+b[0];c[1]=
a[1]+b[1];c[2]=a[2]+b[2];return c},neg:function(a,b){void 0===b&&(b=[]);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},lerp:function(a,b,c,d){void 0===d&&(d=[]);var e=1-a;d[0]=b[0]*e+a*c[0];d[1]=b[1]*e+a*c[1];d[2]=b[2]*e+a*c[2];return d}},Vec4:{dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]},copy:function(a,b){void 0===b&&(b=[]);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},sub:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];c[3]=a[3]-b[3];return c},
mult:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;c[3]=a[3]*b;return c},add:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];c[3]=a[3]+b[3];return c},neg:function(a,b){void 0===b&&(b=[]);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=-a[3];return b},lerp:function(a,b,c,d){void 0===d&&(d=[]);var e=1-a;d[0]=b[0]*e+a*c[0];d[1]=b[1]*e+a*c[1];d[2]=b[2]*e+a*c[2];d[3]=b[3]*e+a*c[3];return d}},Quat:{makeIdentity:function(a){return osg.Quat.init(a)},init:function(a){void 0===
a&&(a=[]);a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a},sub:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];c[3]=a[3]-b[3];return c},add:function(a,b,c){void 0===c&&(c=[]);c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];c[3]=a[3]+b[3];return c},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]},length2:function(a){return a[0]*a[0]+a[1]*a[1]+a[2]*a[2]+a[3]*a[3]},neg:function(a,b){void 0===b&&(b=[]);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=-a[3];return b},makeRotate:function(a,
b,c,d,e){var f=Math.sqrt(b*b+c*c+d*d);if(1E-7>f)return this.init();var f=1/f,g=Math.cos(.5*a);a=Math.sin(.5*a);void 0===e&&(e=[]);e[0]=b*a*f;e[1]=c*a*f;e[2]=d*a*f;e[3]=g;return e},lerp:function(a,b,c,d){void 0===d&&(d=[]);c=1-a;d[0]=b[0]*c+quatTo[0]*a;d[1]=b[1]*c+quatTo[1]*a;d[2]=b[2]*c+quatTo[2]*a;d[3]=b[3]*c+quatTo[3]*a;return d},slerp:function(a,b,c,d){var e=c,f=this.dot(b,e);0>f&&(f=-f,e=this.neg(c));var g;1E-5<1-f?(f=Math.acos(f),g=Math.sin(f),c=Math.sin((1-a)*f)/g,a=Math.sin(a*f)/g):c=1-a;void 0===
d&&(d=[]);d[0]=b[0]*c+e[0]*a;d[1]=b[1]*c+e[1]*a;d[2]=b[2]*c+e[2]*a;d[3]=b[3]*c+e[3]*a;return d},conj:function(a,b){void 0===b&&(b=[]);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},inverse:function(a,b){void 0===b&&(b=[]);var c=1/this.length2(a);this.conj(a,b);b[0]*=c;b[1]*=c;b[2]*=c;b[3]*=c;return b},mult:function(a,b,c){void 0===c&&(c=[]);var d=b[3]*a[0]+b[0]*a[3]+b[1]*a[2]-b[2]*a[1],e=b[3]*a[1]-b[0]*a[2]+b[1]*a[3]+b[2]*a[0],f=b[3]*a[2]+b[0]*a[1]-b[1]*a[0]+b[2]*a[3];c[3]=b[3]*a[3]-b[0]*a[0]-
b[1]*a[1]-b[2]*a[2];c[0]=d;c[1]=e;c[2]=f;return c},div:function(a,b,c){void 0===c&&(c=[]);b=1/b;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;c[3]=a[3]*b;return c},exp:function(a,b){var c=Math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2]),d=Math.exp(a[3]),e=0;1E-5<c&&(e=d*Math.sin(c)/c);void 0===b&&(b=[]);b[0]=e*a[0];b[1]=e*a[1];b[2]=e*a[2];b[3]=d*Math.cos(c);return b},ln:function(a,b){var c=a[0]*a[0]+a[1]*a[1]+a[2]*a[2],d=Math.sqrt(c),e=0;1E-5<d&&(e=Math.atan2(d,a[3])/d);void 0===b&&(b=[]);c+=a[3]*a[3];b[0]=e*a[0];
b[1]=e*a[1];b[2]=e*a[2];b[3]=.5*Math.log(c);return b},squad:function(a,b,c,d,e,f){b=this.slerp(a,b,e);c=this.slerp(a,c,d);return this.slerp(2*a*(1-a),b,c,f)},computeTangent:function(a,b,c,d){void 0===d&&(d=[]);b=this.inv(b);this.mult(b,c,void 0);this.ln(void 0,void 0);this.mult(b,a,void 0);this.ln(void 0,void 0);this.add(void 0,void 0,void 0);this.div(void 0,-4,void 0);this.exp(void 0,void 0);return this.mult(q1,void 0,d)},createKey:function(a,b){void 0===b?b=this.init():a!==b&&(b[0]=a[0],b[1]=a[1],
b[2]=a[2],b[3]=a[3]);b.time=0;b.tangent=[];return b}},Uniform:function(){this.transpose=!1}};osg.Uniform.prototype={set:function(a){this.data=a;this.dirty=!0},apply:function(a){this.dirty&&this.glData.set(this.data);this.glCall(a,this.glData)},applyMatrix:function(a){this.dirty&&this.glData.set(this.data);this.glCall(a,this.transpose,this.glData)}};
osg.Uniform.createFloat1=function(a,b){var c=new osg.Uniform;c.data=[a];c.glCall=function(a,b){gl.uniform1fv(a,b)};c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Uniform.createFloat2=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform2fv(a,b)};c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};
osg.Uniform.createFloat3=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform3fv(a,b)};c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Uniform.createFloat4=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform4fv(a,b)};c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};
osg.Uniform.createInt1=function(a,b){var c=new osg.Uniform;c.data=[a];c.glCall=function(a,b){gl.uniform1iv(a,b)};c.glData=new Int32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Uniform.createInt2=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform2iv(a,b)};c.glData=new Int32Array(c.data);c.dirty=!1;c.name=b;return c};
osg.Uniform.createInt3=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform3iv(a,b)};c.glData=new Int32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Uniform.createInt4=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b){gl.uniform4iv(a,b)};c.glData=new Int32Array(c.data);c.dirty=!1;c.name=b;return c};
osg.Uniform.createMatrix2=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b,c){gl.uniformMatrix2fv(a,b,c)};c.apply=c.applyMatrix;c.transpose=!1;c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Uniform.createMatrix3=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b,c){gl.uniformMatrix3fv(a,b,c)};c.apply=c.applyMatrix;c.transpose=!1;c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};
osg.Uniform.createMatrix4=function(a,b){var c=new osg.Uniform;c.data=a;c.glCall=function(a,b,c){gl.uniformMatrix4fv(a,b,c)};c.apply=c.applyMatrix;c.transpose=!1;c.glData=new Float32Array(c.data);c.dirty=!1;c.name=b;return c};osg.Stack=function(){};osg.Stack.create=function(){var a=[];a.globalDefault=void 0;a.lastApplied=void 0;a.back=function(){return this[this.length-1]};return a};osg.ShaderGeneratorType={VertexInit:0,VertexFunction:1,VertexMain:2,FragmentInit:3,FragmentMain:5};osg.Shader=function(){};
osg.Shader.prototype={compile:function(){this.shader=gl.createShader(this.type);gl.shaderSource(this.shader,this.text);gl.compileShader(this.shader);if(!gl.getShaderParameter(this.shader,gl.COMPILE_STATUS))if(void 0!==console){console.log("can't compile shader:\n"+this.text+"\n");for(var a=("\n"+this.text).split("\n"),b="\n",c=0,d=a.length;c<d;++c)b+=c+" "+a[c]+"\n";console.log(b);console.log(gl.getShaderInfoLog(this.shader));debugger}else alert(gl.getShaderInfoLog(this.shader))}};
osg.Shader.create=function(a,b){var c=new osg.Shader(a);c.type=a;c.text=b;return c};osg.Program=function(){};
osg.Program.prototype={attributeType:"Program",cloneType:function(){var a=osg.Program.create();a.default_program=!0;return a},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},setVertexShader:function(a){program.vertex=a},setFragmentShader:function(a){program.fragment=a},apply:function(a){if(!this.program||this.dirty){if(!0===this.default_program)return;this.vertex.shader||this.vertex.compile();this.fragment.shader||this.fragment.compile();this.program=
gl.createProgram();gl.attachShader(this.program,this.vertex.shader);gl.attachShader(this.program,this.fragment.shader);gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS)){osg.log("can't link program\n"+this.vertex.text+this.fragment.text);osg.log(gl.getProgramInfo(this.program));debugger;return null}this.uniformsCache={};this.uniformsCache.uniformKeys=[];this.attributesCache={};this.attributesCache.attributeKeys=[];this.cacheUniformList(this.vertex.text);this.cacheUniformList(this.fragment.text);
this.cacheAttributeList(this.vertex.text);this.dirty=!1}gl.useProgram(this.program)},cacheUniformList:function(a){a=a.match(/uniform\s+\w+\s+\w+/g);if(null!==a)for(var b in a){var c=a[b].match(/uniform\s+\w+\s+(\w+)/)[1],d=gl.getUniformLocation(this.program,c);void 0!==d&&null!==d&&void 0===this.uniformsCache[c]&&(this.uniformsCache[c]=d,this.uniformsCache.uniformKeys.push(c))}},cacheAttributeList:function(a){a=a.match(/attribute\s+\w+\s+\w+/g);if(null!==a)for(var b in a){var c=a[b].match(/attribute\s+\w+\s+(\w+)/)[1],
d=gl.getAttribLocation(this.program,c);-1!==d&&void 0!==d&&void 0===this.attributesCache[c]&&(this.attributesCache[c]=d,this.attributesCache.attributeKeys.push(c))}}};osg.Program.create=function(a,b){var c=new osg.Program;c.program=null;c.vertex=a;c.fragment=b;c.dirty=!0;return c};osg.ShaderGenerator=function(){this.cache=[]};
osg.ShaderGenerator.prototype={getActiveTypeMember:function(a){for(var b=[],c=0,d=a.attributeMap.attributeKeys.length;c<d;c++){var e=a.attributeMap.attributeKeys[c],f=a.attributeMap[e];if(0!==f.length||void 0!==f.globalDefault.applyPositionedUniform)void 0===f.globalDefault.getOrCreateUniforms&&void 0===f.globalDefault.writeToShader||b.push(e)}c=0;for(d=a.textureAttributeMapList.length;c<d;c++)if(e=a.textureAttributeMapList[c],void 0!==e)for(var f=0,g=e.attributeKeys.length;f<g;f++){var h=e.attributeKeys[f],
k=e[h];0!==k.length&&(void 0===k.globalDefault.getOrCreateUniforms&&void 0===k.globalDefault.writeToShader||b.push(h+c))}return b},getActiveAttributeMapKeys:function(a){for(var b=[],c=0,d=a.attributeMap.attributeKeys.length;c<d;c++){var e=a.attributeMap.attributeKeys[c],f=a.attributeMap[e];if(0!==f.length||void 0!==f.globalDefault.applyPositionedUniform)void 0===f.globalDefault.getOrCreateUniforms&&void 0===f.globalDefault.writeToShader||b.push(e)}return b},getActiveTextureAttributeMapKeys:function(a){for(var b=
Array(a.textureAttributeMapList.length),c=0,d=a.textureAttributeMapList.length;c<d;c++){var e=a.textureAttributeMapList[c];if(void 0!==e){b[c]=[];for(var f=0,g=e.attributeKeys.length;f<g;f++){var h=e.attributeKeys[f],k=e[h];0!==k.length&&(void 0===k.globalDefault.getOrCreateUniforms&&void 0===k.globalDefault.writeToShader||b[c].push(h))}}}return b},getActiveUniforms:function(a,b,c){for(var d={},e=0,f=b.length;e<f;e++){var g=b[e];if(void 0!==a.attributeMap[g].globalDefault.getOrCreateUniforms)for(var g=
a.attributeMap[g].globalDefault.getOrCreateUniforms(),h=0,k=g.uniformKeys.length;h<k;h++){var m=g[g.uniformKeys[h]];d[m.name]=m}}b=0;for(e=c.length;b<e;b++)if(f=c[b],void 0!==f)for(g=0,h=f.length;g<h;g++){k=f[g];if(void 0===a.textureAttributeMapList[b][k].globalDefault)debugger;k=a.textureAttributeMapList[b][k].globalDefault;if(void 0!==k.getOrCreateUniforms)for(var k=k.getOrCreateUniforms(b),m=0,p=k.uniformKeys.length;m<p;m++){var n=k[k.uniformKeys[m]];d[n.name]=n}}a=[];for(var q in d)a.push(q);
d.uniformKeys=a;return d},getOrCreateProgram:function(a){for(var b=this.getActiveTypeMember(a),c=0,d=this.cache.length;c<d;++c)if(0===this.compareAttributeMap(b,this.cache[c].flattenKeys))return this.cache[c];var c=this.getActiveAttributeMapKeys(a),d=this.getActiveTextureAttributeMapKeys(a),e=this.getOrCreateVertexShader(a,c,d),f=this.getOrCreateFragmentShader(a,c,d),e=osg.Program.create(osg.Shader.create(gl.VERTEX_SHADER,e),osg.Shader.create(gl.FRAGMENT_SHADER,f));e.flattenKeys=b;e.activeAttributeKeys=
c;e.activeTextureAttributeKeys=d;e.activeUniforms=this.getActiveUniforms(a,c,d);e.generated=!0;osg.log(e.vertex.text);osg.log(e.fragment.text);this.cache.push(e);return e},compareAttributeMap:function(a,b){for(var c,d=0,e=a.length;d<e;d++)if(c=a[d],-1===b.indexOf(c))return 1;return b.length!==a.length?-1:0},fillTextureShader:function(a,b,c){for(var d="",e={},f=0,g=b.length;f<g;f++){var h=b[f];if(void 0!==h)for(var k=a[f],m=0,p=h.length;m<p;m++){var n=h[m],q=k[n].globalDefault;void 0!==q.writeShaderInstance&&
void 0===e[n]&&(d+=q.writeShaderInstance(f,c),e[n]=!0);q.writeToShader&&(d+=q.writeToShader(f,c))}}return d},fillShader:function(a,b,c){for(var d="",e={},f=0,g=b.length;f<g;f++){var h=b[f],k=a[h].globalDefault;void 0!==k.writeShaderInstance&&void 0===e[h]&&(d+=k.writeShaderInstance(c),e[h]=!0);k.writeToShader&&(d+=k.writeToShader(c))}return d},getOrCreateVertexShader:function(a,b,c){var d=osg.ShaderGeneratorType.VertexInit,e;e="\n#ifdef GL_ES\nprecision highp float;\n#endif\nattribute vec3 Vertex;\nattribute vec3 Normal;\nuniform mat4 ModelViewMatrix;\nuniform mat4 ProjectionMatrix;\nuniform mat4 NormalMatrix;\n"+
this.fillTextureShader(a.textureAttributeMapList,c,d);e+=this.fillShader(a.attributeMap,b,d);d=osg.ShaderGeneratorType.VertexFunction;e=e+"\nvec4 ftransform() {\nreturn ProjectionMatrix * ModelViewMatrix * vec4(Vertex, 1.0);\n}"+this.fillTextureShader(a.textureAttributeMapList,c,d);e+=this.fillShader(a.attributeMap,b,d);e+="\nvoid main(void) {\ngl_Position = ftransform();\n";d=osg.ShaderGeneratorType.VertexMain;e+=this.fillTextureShader(a.textureAttributeMapList,c,d);e+=this.fillShader(a.attributeMap,
b,d);return e+="}\n"},getOrCreateFragmentShader:function(a,b,c){var d,e,f=osg.ShaderGeneratorType.FragmentInit;e="\n#ifdef GL_ES\nprecision highp float;\n#endif\nvec4 fragColor;\n"+this.fillTextureShader(a.textureAttributeMapList,c,f);e+=this.fillShader(a.attributeMap,b,f);e+="void main(void) {\nfragColor = vec4(1.0, 1.0, 1.0, 1.0);\n";f=osg.ShaderGeneratorType.FragmentMain;if(0<c.length)for(d=this.fillTextureShader(a.textureAttributeMapList,c,f),e+=d,d=0,l=c.length;d<l;++d)void 0!==c[d]&&0!==c[d].length&&
void 0!==a.textureAttributeMapList[d].Texture&&(e+="fragColor = fragColor * texColor"+d+";\n");e+=this.fillShader(a.attributeMap,b,f);return e+"\ngl_FragColor = fragColor;\n}"}};
osg.State=function(){this.currentVBO=null;this.vertexAttribList=[];this.programs=osg.Stack.create();this.stateSets=osg.Stack.create();this.uniforms={};this.uniforms.uniformKeys=[];this.textureAttributeMapList=[];this.attributeMap={};this.attributeMap.attributeKeys=[];this.modeMap={};this.shaderGenerator=new osg.ShaderGenerator;this.modelViewMatrix=osg.Uniform.createMatrix4(osg.Matrix.makeIdentity(),"ModelViewMatrix");this.projectionMatrix=osg.Uniform.createMatrix4(osg.Matrix.makeIdentity(),"ProjectionMatrix");
this.normalMatrix=osg.Uniform.createMatrix4(osg.Matrix.makeIdentity(),"NormalMatrix")};
osg.State.prototype={applyModelViewAndProjectionMatrix:function(a,b){this.modelViewMatrix.set(a);this.projectionMatrix.set(b);var c=osg.Matrix.copy(a);osg.Matrix.setTrans(c,0,0,0);osg.Matrix.inverse(c,c);this.normalMatrix.set(c);this.getLastProgramApplied()},pushStateSet:function(a){this.stateSets.push(a);a.attributeMap&&this.pushAttributeMap(this.attributeMap,a.attributeMap);if(a.textureAttributeMapList)for(var b=a.textureAttributeMapList,c=0,d=b.length;c<d;c++)void 0!==b[c]&&(this.textureAttributeMapList[c]||
(this.textureAttributeMapList[c]={},this.textureAttributeMapList[c].attributeKeys=[]),this.pushAttributeMap(this.textureAttributeMapList[c],b[c]));a.uniforms&&this.pushUniformsList(this.uniforms,a.uniforms)},applyStateSet:function(a){this.pushStateSet(a);this.apply();this.popStateSet()},popStateSet:function(){var a=this.stateSets.pop();a.program&&this.programs.pop();a.attributeMap&&this.popAttributeMap(this.attributeMap,a.attributeMap);if(a.textureAttributeMapList)for(var b=a.textureAttributeMapList,
c=0,d=b.length;c<d;c++)void 0!==b[c]&&this.popAttributeMap(this.textureAttributeMapList[c],b[c]);a.uniforms&&this.popUniformsList(this.uniforms,a.uniforms)},applyAttribute:function(a){var b=a.getTypeMember(),c=this.attributeMap[b];void 0===c&&(c=osg.Stack.create(),this.attributeMap[b]=c,this.attributeMap[b].globalDefault=a.cloneType(),this.attributeMap.attributeKeys.push(b));c.lastApplied!==a&&(a.apply&&a.apply(this),c.lastApplied=a,c.asChanged=!0)},applyTextureAttribute:function(a,b){var c=b.getTypeMember();
this.textureAttributeMapList[a]||(this.textureAttributeMapList[a]={},this.textureAttributeMapList[a].attributeKeys=[]);var d=this.textureAttributeMapList[a][c];void 0===d&&(d=osg.Stack.create(),this.textureAttributeMapList[a][c]=d,d.globalDefault=b.cloneType(),this.textureAttributeMapList[a].attributeKeys.push(c));d.lastApplied!==b&&(b.apply&&b.apply(this),d.lastApplied=b,d.asChanged=!0)},getLastProgramApplied:function(){return this.programs.lastApplied},pushGeneratedProgram:function(){var a;if(void 0!==
this.attributeMap.Program&&(a=this.attributeMap.Program.back(),void 0!==a))return this.programs.push(a),a;a=this.shaderGenerator.getOrCreateProgram({textureAttributeMapList:this.textureAttributeMapList,attributeMap:this.attributeMap});this.programs.push(a);return a},popGeneratedProgram:function(){this.programs.pop()},apply:function(){this.applyAttributeMap(this.attributeMap);this.applyTextureAttributeMapList(this.textureAttributeMapList);this.pushGeneratedProgram();var a=this.programs.back();this.programs.lastApplied!==
a&&(a.apply(this),this.programs.lastApplied=a);if(void 0!==a.generated&&!0===a.generated){for(var b=a.uniformsCache,a=a.activeUniforms,c=!1,d=0,e=a.uniformKeys.length;d<e;d++){var f=a.uniformKeys[d],g=b[f];void 0!==g?a[f].apply(g):(c=!0,delete a[f])}if(c){var b=[],h;for(h in a)"uniformKeys"!==h&&b.push(h);a.uniformKeys=b}}else this.applyUniformList(this.uniforms,{})},applyUniformList:function(a,b){for(var c,d,e=this.getLastProgramApplied().uniformsCache,f=0,g=e.uniformKeys.length;f<g;f++){var h=e.uniformKeys[f];
c=e[h];d=b[h];if(void 0===d){d=a[h];if(void 0===d)continue;d=0===d.length?d.globalDefault:d.back()}d.apply(c)}},applyAttributeMap:function(a){for(var b,c=0,d=a.attributeKeys.length;c<d;c++)if(b=a[a.attributeKeys[c]],void 0!==b){var e;e=0===b.length?b.globalDefault:b.back();b.lastApplied!==e&&(e.apply&&e.apply(this),b.lastApplied=e,b.asChanged=!0)}},pushUniformsList:function(a,b){for(var c,d,e=0,f=b.uniformKeys.length;e<f;e++)d=b[b.uniformKeys[e]],c=d.name,void 0===a[c]&&(a[c]=osg.Stack.create(),a[c].globalDefault=
d,a.uniformKeys.push(c)),a[c].push(d)},popUniformsList:function(a,b){for(var c=0,d=b.uniformKeys.length;c<d;c++)a[b.uniformKeys[c]].pop()},applyTextureAttributeMapList:function(a){for(var b,c=0,d=a.length;c<d;c++)if(b=a[c],void 0!==b)for(var e=0,f=b.attributeKeys.length;e<f;e++){var g=b[b.attributeKeys[e]];if(void 0!==g){var h;h=0===g.length?g.globalDefault:g.back();g.lastApplied!==h&&(gl.activeTexture(gl.TEXTURE0+c),h.apply(this.state),g.lastApplied=h)}}},setGlobalDefaultValue:function(a){var b=
a.getTypeMember();this.attributeMap[b]?this.attributeMap[b].globalDefault=a:(this.attributeMap[b]=osg.Stack.create(),this.attributeMap[b].globalDefault=a,this.attributeMap.attributeKeys.push(b))},pushAttributeMap:function(a,b){for(var c,d=0,e=b.attributeKeys.length;d<e;d++){c=b.attributeKeys[d];var f=b[c];void 0===a[c]&&(a[c]=osg.Stack.create(),a[c].globalDefault=f.cloneType(),a.attributeKeys.push(c));c=a[c];c.push(f);c.asChanged=!0}},popAttributeMap:function(a,b){for(var c,d=0,e=b.attributeKeys.length;d<
e;d++)type=b.attributeKeys[d],c=a[type],c.pop(),c.asChanged=!0},disableVertexAttribsExcept:function(a){for(var b=this.vertexAttribList.filter(function(b,c,d){return 0>a.indexOf(b)}),c=0,d=b.length;c<d;c++)gl.disableVertexAttribArray(b[c]);this.vertexAttribList=a},setIndexArray:function(a){this.currentIndexVBO!==a&&(a.buffer||a.init(),gl.bindBuffer(a.type,a.buffer),this.currentIndexVBO=a);a.dirty&&a.compile()},setVertexAttribArray:function(a,b,c){b.buffer||b.init();gl.bindBuffer(b.type,b.buffer);b.dirty&&
b.compile();this.vertexAttribList.push(a);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,b.itemSize,gl.FLOAT,c,0,0)}};osg.State.create=function(){var a=new osg.State;gl.hint(gl.NICEST,gl.GENERATE_MIPMAP_HINT);return a};osg.StateSet=function(){this.id=osg.instance++};
osg.StateSet.prototype={addUniform:function(a){this.uniforms||(this.uniforms={},this.uniforms.uniformKeys=[]);var b=a.name;this.uniforms[b]=a;-1===this.uniforms.uniformKeys.indexOf(b)&&this.uniforms.uniformKeys.push(b)},getUniformMap:function(){return this.uniforms},setTextureAttributeAndMode:function(a,b,c){this.setTextureAttribute(a,b)},setTextureAttribute:function(a,b){this.textureAttributeMapList||(this.textureAttributeMapList=[]);void 0===this.textureAttributeMapList[a]&&(this.textureAttributeMapList[a]=
{},this.textureAttributeMapList[a].attributeKeys=[]);var c=b.getTypeMember();this.textureAttributeMapList[a][c]=b;-1===this.textureAttributeMapList[a].attributeKeys.indexOf(c)&&this.textureAttributeMapList[a].attributeKeys.push(c)},setTexture:function(a,b){this.setTextureAttribute(a,b)},getTextureAttributeMap:function(a){return this.textureAttributeMapList[a]},setAttributeAndMode:function(a){this.setAttribute(a)},setAttribute:function(a){this.attributeMap||(this.attributeMap={},this.attributeMap.attributeKeys=
[]);var b=a.getTypeMember();this.attributeMap[b]=a;-1===this.attributeMap.attributeKeys.indexOf(b)&&this.attributeMap.attributeKeys.push(b)},getAttributeMap:function(){return this.attributeMap}};osg.StateSet.create=function(){return new osg.StateSet};osg.Node=function(){this.children=[];this.nodeMask=-1};
osg.Node.prototype={getOrCreateStateSet:function(){void 0===this.stateset&&(this.stateset=new osg.StateSet);return this.stateset},getStateSet:function(){return this.stateset},accept:function(a){a.validNodeMask(this)&&a.apply(this)},setNodeMask:function(a){this.nodeMask=a},getNodeMask:function(a){return this.nodeMask},setStateSet:function(a){this.stateset=a},setUpdateCallback:function(a){this.updateCallback=a},getUpdateCallback:function(){return this.updateCallback},setName:function(a){this.name=a},
getName:function(){return this.name},addChild:function(a){return this.children.push(a)},getChildren:function(){return this.children},removeChildren:function(){this.children.length=0},removeChildOld:function(a){for(var b=0,c=this.children.length;b<c;b++)this.children[b]===a&&(b!=c-1&&(this.children[b]=this.children[c-1]),this.children.pop())},removeChild:function(a){for(var b=0,c=this.children.length;b<c;b++)this.children[b]===a&&this.children.splice(b,1)},traverse:function(a){for(var b=0,c=this.children.length;b<
c;b++)this.children[b].accept(a)},traverseNew:function(a){for(var b=0,c=this.children.length;b<c;b++){var d=this.children[b];a.validNodeMask(d)&&a.apply(d)}}};osg.Node.create=function(){return new osg.Node};osg.MatrixTransform=function(){osg.Node.call(this);this.matrix=osg.Matrix.makeIdentity()};osg.MatrixTransform.prototype=osg.objectInehrit(osg.Node.prototype,{getMatrix:function(){return this.matrix},setMatrix:function(a){this.matrix=a}});osg.MatrixTransform.create=function(){return new osg.MatrixTransform};
osg.Projection=function(){osg.Node.call(this);this.projection=osg.Matrix.makeIdentity()};osg.Projection.prototype=osg.objectInehrit(osg.Node.prototype,{getProjectionMatrix:function(){return this.projection},setProjectionMatrix:function(a){this.projection=a}});osg.Projection.create=function(){return new osg.Projection};osg.Texture=function(){this.mag_filter="LINEAR";this.min_filter="LINEAR_MIPMAP_LINEAR";this.wrap_t=this.wrap_s="CLAMP_TO_EDGE";this.textureHeight=this.textureWidth=0;this.target="TEXTURE_2D"};
osg.Texture.prototype={attributeType:"Texture",cloneType:function(){var a=new osg.Texture;a.default_type=!0;return a},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},getOrCreateUniforms:function(a){void 0===osg.Texture.uniforms&&(osg.Texture.uniforms=[]);if(void 0===osg.Texture.uniforms[a]){var b=this.getType()+a,c={};c[b]=osg.Uniform.createInt1(a,b);c.uniformKeys=[b];osg.Texture.uniforms[a]=c}return osg.Texture.uniforms[a]},setTextureSize:function(a,
b){this.textureWidth=a;this.textureHeight=b},init:function(){this.textureObject||(this.textureObject=gl.createTexture(),this.dirty=!0)},getWidth:function(){return this.textureWidth},getHeight:function(){return this.textureHeight},setWrapS:function(a){this.wrap_s=a},setWrapT:function(a){this.wrap_t=a},setMinFilter:function(a){this.min_filter=a},setMagFilter:function(a){this.mag_filter=a},setImage:function(a){this.image=a;this.dirty=!0},setFromCanvas:function(a){this.init();gl.bindTexture(gl.TEXTURE_2D,
this.textureObject);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,a);this.setTextureSize(a.width,a.height);this.applyFilterParameter();this.dirty=!1},isImageReady:function(){var a=this.image;return a&&a.complete?"undefined"!==typeof a.naturalWidth&&0===a.naturalWidth?!1:!0:!1},compile:function(){var a=this.image;a&&a.complete&&("undefined"===typeof a.naturalWidth||0!==a.naturalWidth)&&(gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,a),this.applyFilterParameter(),this.dirty=
!1)},applyFilterParameter:function(){gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl[this.mag_filter]);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl[this.min_filter]);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl[this.wrap_s]);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl[this.wrap_t]);"NEAREST_MIPMAP_NEAREST"!==this.min_filter&&"LINEAR_MIPMAP_NEAREST"!==this.min_filter&&"NEAREST_MIPMAP_LINEAR"!==this.min_filter&&"LINEAR_MIPMAP_LINEAR"!==this.min_filter||gl.generateMipmap(gl.TEXTURE_2D)},
apply:function(a){void 0!==this.image?this.textureObject?gl.bindTexture(gl.TEXTURE_2D,this.textureObject):this.isImageReady()?(this.textureObject||this.init(),gl.bindTexture(gl.TEXTURE_2D,this.textureObject),gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,this.image),this.applyFilterParameter()):gl.bindTexture(gl.TEXTURE_2D,null):0!==this.textureHeight&&0!==this.textureWidth?this.textureObject?gl.bindTexture(gl.TEXTURE_2D,this.textureObject):(this.init(),gl.bindTexture(gl.TEXTURE_2D,
this.textureObject),gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,this.textureWidth,this.textureHeight,0,gl.RGBA,gl.UNSIGNED_BYTE,null),this.applyFilterParameter()):void 0!==this.textureObject?gl.bindTexture(gl.TEXTURE_2D,this.textureObject):gl.bindTexture(gl.TEXTURE_2D,null)},writeToShader:function(a,b){var c="";switch(b){case osg.ShaderGeneratorType.VertexInit:c="attribute vec2 TexCoord"+a+";\n"+("varying vec2 FragTexCoord"+a+";\n");break;case osg.ShaderGeneratorType.VertexMain:c="FragTexCoord"+a+" = TexCoord"+
a+";\n";break;case osg.ShaderGeneratorType.FragmentInit:c="varying vec2 FragTexCoord"+a+";\n"+("uniform sampler2D Texture"+a+";\n");c+="vec4 texColor"+a+";\n";break;case osg.ShaderGeneratorType.FragmentMain:c="texColor"+a+" = texture2D( Texture"+a+", FragTexCoord"+a+".xy );\n"}return c}};osg.Texture.create=function(a){var b=new osg.Texture;b.dirty=!0;if(void 0!==a){var c=new Image;c.src=a;b.setImage(c)}return b};
osg.Texture.createFromImg=function(a){var b=new osg.Texture;b.dirty=!0;b.setImage(a);return b};osg.Texture.createFromCanvas=function(a){var b=new osg.Texture;b.setFromCanvas(a);return b};osg.Depth=function(a,b,c,d){this.func="LESS";this.near=0;this.far=1;this.writeMask=!0;void 0!==a&&(this.func=a);void 0!==b&&(this.near=b);void 0!==c&&(this.far=c);void 0!==d&&(this.writeMask=c)};
osg.Depth.prototype={attributeType:"Depth",cloneType:function(){return new osg.Depth},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},setRange:function(a,b){this.near=a;this.far=b},setWriteMask:function(a){this.mask=a},apply:function(a){"DISABLE"===this.func?gl.disable(gl.DEPTH_TEST):(gl.enable(gl.DEPTH_TEST),gl.depthFunc(gl[this.func]),gl.depthMask(this.writeMask),gl.depthRange(this.near,this.far))}};
osg.BlendFunc=function(a,b){this.sourceFactor="ONE";this.destinationFactor="ZERO";void 0!==a&&(this.sourceFactor=a);void 0!==b&&(this.destinationFactor=b)};osg.BlendFunc.prototype={attributeType:"BlendFunc",cloneType:function(){return new osg.BlendFunc},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},apply:function(a){gl.blendFunc(gl[this.sourceFactor],gl[this.destinationFactor])}};
osg.LineWidth=function(a){this.lineWidth=1;void 0!==a&&(this.lineWidth=a)};osg.LineWidth.prototype={attributeType:"LineWidth",cloneType:function(){return new osg.LineWidth},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},apply:function(a){gl.lineWidth(this.lineWidth)}};osg.CullFace=function(a){this.mode="BACK";void 0!==a&&(this.mode=a)};
osg.CullFace.prototype={attributeType:"CullFace",cloneType:function(){return new osg.CullFace},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},apply:function(a){"DISABLE"===this.mode?gl.disable(gl.CULL_FACE):(gl.enable(gl.CULL_FACE),gl.cullFace(gl[this.mode]))}};osg.FrameBufferObject=function(){this.fbo=void 0;this.attachments=[]};
osg.FrameBufferObject.prototype={attributeType:"FrameBufferObject",cloneType:function(){return new osg.FrameBufferObject},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},setAttachment:function(a){this.attachments.push(a)},apply:function(a){if(0<this.attachments.length){if(void 0===this.fbo){this.fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);for(var b=0,c=this.attachments.length;b<c;++b){var d=this.attachments[b].texture;a.applyTextureAttribute(1,
d);gl.framebufferTexture2D(gl.FRAMEBUFFER,this.attachments[b].attachment,gl[d.target],d.textureObject,this.attachments[b].level)}}else gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);a=gl.checkFramebufferStatus(gl.FRAMEBUFFER);36053!==a&&osg.log("framebuffer error check "+a)}else gl.bindFramebuffer(gl.FRAMEBUFFER,null)}};
osg.Viewport=function(a,b,c,d){void 0===a&&(a=0);void 0===b&&(b=0);void 0===c&&(c=800);void 0===d&&(d=600);var e=a,f=b,g=c,h=d;this.x=function(){return e};this.y=function(){return f};this.width=function(){return g};this.height=function(){return h};this.computeWindowMatrix=function(){var a=osg.Matrix.makeTranslate(1,1,1),b=osg.Matrix.makeScale(.5*g,.5*h,.5),c=osg.Matrix.makeTranslate(e,f,0);return osg.Matrix.mult(osg.Matrix.mult(a,b,a),c,c)}};
osg.Viewport.prototype={attributeType:"Viewport",cloneType:function(){return new osg.Viewport},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},apply:function(a){gl.viewport(this.x(),this.y(),this.width(),this.height())}};osg.Material=function(){this.ambient=[.2,.2,.2,1];this.diffuse=[.8,.8,.8,1];this.specular=[0,0,0,1];this.emission=[0,0,0,1];this.shininess=[0]};
osg.Material.prototype={attributeType:"Material",cloneType:function(){return new osg.Material},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType},getOrCreateUniforms:function(){if(void 0===osg.Material.uniforms){osg.Material.uniforms={ambient:osg.Uniform.createFloat4([0,0,0,0],"MaterialAmbient"),diffuse:osg.Uniform.createFloat4([0,0,0,0],"MaterialDiffuse"),specular:osg.Uniform.createFloat4([0,0,0,0],"MaterialSpecular"),emission:osg.Uniform.createFloat4([0,
0,0,0],"MaterialEmission"),shininess:osg.Uniform.createFloat1([0],"MaterialShininess")};var a=[],b;for(b in osg.Material.uniforms)a.push(b);osg.Material.uniforms.uniformKeys=a}return osg.Material.uniforms},apply:function(a){a=this.getOrCreateUniforms();a.ambient.set(this.ambient);a.diffuse.set(this.diffuse);a.specular.set(this.specular);a.emission.set(this.emission);a.shininess.set(this.shininess)},writeToShader:function(a){var b="";switch(a){case osg.ShaderGeneratorType.VertexInit:b="uniform vec4 MaterialAmbient;\nuniform vec4 MaterialDiffuse;\nuniform vec4 MaterialSpecular;\nuniform vec4 MaterialEmission;\nuniform float MaterialShininess;\nvec4 Ambient;\nvec4 Diffuse;\nvec4 Specular;\n"}return b}};
osg.Material.create=function(){return new osg.Material};osg.Light=function(){this.ambient=[.2,.2,.2,1];this.diffuse=[.8,.8,.8,1];this.specular=[0,0,0,1];this.direction=[0,0,1];this.quadratic_attenuation=this.linear_attenuation=this.constant_attenuation=1;this.enabled=this.light_unit=0;this.ambient=[1,1,1,1];this.diffuse=[1,1,1,1];this.specular=[1,1,1,1]};
osg.Light.prototype={attributeType:"Light",cloneType:function(){return new osg.Light},getType:function(){return this.attributeType},getTypeMember:function(){return this.attributeType+this.light_unit},getOrCreateUniforms:function(){void 0===osg.Light.uniforms&&(osg.Light.uniforms={});if(void 0===osg.Light.uniforms[this.getTypeMember()]){osg.Light.uniforms[this.getTypeMember()]={ambient:osg.Uniform.createFloat4([.2,.2,.2,1],this.getParameterName("ambient")),diffuse:osg.Uniform.createFloat4([.8,.8,.8,
1],this.getParameterName("diffuse")),specular:osg.Uniform.createFloat4([.2,.2,.2,1],this.getParameterName("specular")),direction:osg.Uniform.createFloat3([0,0,1],this.getParameterName("direction")),constant_attenuation:osg.Uniform.createFloat1(0,this.getParameterName("constant_attenuation")),linear_attenuation:osg.Uniform.createFloat1(0,this.getParameterName("linear_attenuation")),quadratic_attenuation:osg.Uniform.createFloat1(0,this.getParameterName("quadratic_attenuation")),enable:osg.Uniform.createInt1(0,
this.getParameterName("enable")),matrix:osg.Uniform.createMatrix4(osg.Matrix.makeIdentity(),this.getParameterName("matrix"))};var a=[],b;for(b in osg.Light.uniforms[this.getTypeMember()])a.push(b);osg.Light.uniforms[this.getTypeMember()].uniformKeys=a}return osg.Light.uniforms[this.getTypeMember()]},getPrefix:function(){return this.getType()+this.light_unit},getParameterName:function(a){return this.getPrefix()+"_"+a},applyPositionedUniform:function(a,b){this.getOrCreateUniforms().matrix.set(a)},apply:function(a){a=
this.getOrCreateUniforms();a.ambient.set(this.ambient);a.diffuse.set(this.diffuse);a.specular.set(this.specular);a.direction.set(this.direction);a.constant_attenuation.set([this.constant_attenuation]);a.linear_attenuation.set([this.linear_attenuation]);a.quadratic_attenuation.set([this.quadratic_attenuation]);a.enable.set([this.enable])},writeShaderInstance:function(a){var b="";switch(a){case osg.ShaderGeneratorType.VertexInit:b="\nvarying vec4 Color;\nvec3 EyeVector;\nvec3 NormalComputed;\n\n";break;
case osg.ShaderGeneratorType.VertexFunction:b="\nvec3 computeNormal() {\n   return vec3(NormalMatrix * vec4(Normal, 0.0));\n}\n\nvec3 computeEyeDirection() {\n   return vec3(ModelViewMatrix * vec4(Vertex,1.0));\n}\n\nvoid directionalLight(in vec3 lightDirection, in vec3 lightHalfVector, in float constantAttenuation, in float linearAttenuation, in float quadraticAttenuation, in vec4 ambient, in vec4 diffuse,in vec4 specular, in vec3 normal)\n{\n   float nDotVP;         // normal . light direction\n   float nDotHV;         // normal . light half vector\n   float pf;             // power factor\n\n   nDotVP = max(0.0, dot(normal, normalize(lightDirection)));\n   nDotHV = max(0.0, dot(normal, lightHalfVector));\n\n   if (nDotHV == 0.0)\n   {\n       pf = 0.0;\n   }\n   else\n   {\n       pf = pow(nDotHV, MaterialShininess);\n   }\n   Ambient  += ambient;\n   Diffuse  += diffuse * nDotVP;\n   Specular += specular * pf;\n}\n\nvoid flight(in vec3 lightDirection, in float constantAttenuation, in float linearAttenuation, in float quadraticAttenuation, in vec4 ambient, in vec4 diffuse, in vec4 specular, in vec3 normal)\n{\n    vec4 localColor;\n    vec3 lightHalfVector = normalize(EyeVector-lightDirection);\n    // Clear the light intensity accumulators\n    Ambient  = vec4 (0.0);\n    Diffuse  = vec4 (0.0);\n    Specular = vec4 (0.0);\n\n    directionalLight(lightDirection, lightHalfVector, constantAttenuation, linearAttenuation, quadraticAttenuation, ambient, diffuse, specular, normal);\n\n    vec4 sceneColor = vec4(0,0,0,0);\n    localColor = sceneColor +\n      MaterialEmission +\n      Ambient  * MaterialAmbient +\n      Diffuse  * MaterialDiffuse;\n      //Specular * MaterialSpecular;\n    localColor = clamp( localColor, 0.0, 1.0 );\n    Color += localColor;\n\n}";
break;case osg.ShaderGeneratorType.VertexMain:b="\nEyeVector = computeEyeDirection();\nNormalComputed = computeNormal();\nColor = vec4(0,0,0,0);\n";break;case osg.ShaderGeneratorType.FragmentInit:b="varying vec4 Color;\n";break;case osg.ShaderGeneratorType.FragmentMain:b="\nfragColor *= Color;"}return b},writeToShader:function(a){var b="";switch(a){case osg.ShaderGeneratorType.VertexInit:b=["","uniform bool "+this.getParameterName("enabled")+";","uniform vec4 "+this.getParameterName("ambient")+";",
"uniform vec4 "+this.getParameterName("diffuse")+";","uniform vec4 "+this.getParameterName("specular")+";","uniform vec3 "+this.getParameterName("direction")+";","uniform float "+this.getParameterName("constantAttenuation")+";","uniform float "+this.getParameterName("linearAttenuation")+";","uniform float "+this.getParameterName("quadraticAttenuation")+";","\n"].join("\n");break;case osg.ShaderGeneratorType.VertexMain:a=this.getParameterName("direction");var b=this.getParameterName("directionNormalized"),
c=this.getParameterName("NdotL"),b=["","//if ("+this.getParameterName("enabled")+") {","if (true) {","  vec3 "+b+" = normalize("+a+");","  float "+c+" = max(dot(Normal, "+b+"), 0.0);","  flight("+b+", "+this.getParameterName("constantAttenuation")+", "+this.getParameterName("linearAttenuation")+", "+this.getParameterName("quadraticAttenuation")+", "+this.getParameterName("ambient")+", "+this.getParameterName("diffuse")+", "+this.getParameterName("specular")+", NormalComputed );","}\n"].join("\n")}return b}};
osg.Light.create=function(){return new osg.Light};osg.BufferArray=function(){};osg.BufferArray.prototype={init:function(){!this.buffer&&0<this.elements.length&&(this.buffer=gl.createBuffer(),this.buffer.itemSize=this.itemSize,this.buffer.numItems=this.elements.length/this.itemSize)},setDirty:function(){this.dirty=!0},compile:function(){this.dirty&&(gl.bufferData(this.type,this.elements,gl.STATIC_DRAW),this.dirty=!1)},getElements:function(){return this.elements}};
osg.BufferArray.create=function(a,b,c){var d=new osg.BufferArray;d.itemSize=c;d.type=a;d.elements=d.type===gl.ELEMENT_ARRAY_BUFFER?new Uint16Array(b):new Float32Array(b);d.dirty=!0;return d};osg.DrawArray=function(a,b,c){this.mode=a;this.first=b;this.count=c};osg.DrawArray.prototype={draw:function(a){gl.drawArrays(this.mode,this.first,this.count)},getMode:function(){return this.mode},getCount:function(){return this.count},getFirst:function(){return this.first}};
osg.DrawArray.create=function(a,b,c){return new osg.DrawArray(a,b,c)};osg.DrawArrays=osg.DrawArray;osg.DrawElements=function(a,b){this.mode=gl.POINTS;void 0!==a&&(this.mode=a);this.offset=this.count=0;this.indices=b;void 0!==b&&(this.count=b.elements.length)};
osg.DrawElements.prototype={getMode:function(){return this.mode},draw:function(a){if(this.count>this.indices.numItems||0>this.count)this.count=this.indices.numItems;a.setIndexArray(this.indices);gl.drawElements(this.mode,this.count,gl.UNSIGNED_SHORT,this.offset)},getIndices:function(){return this.indices},setFirst:function(a){this.offset=a},getFirst:function(){return this.offset},setCount:function(a){this.count=a},getCount:function(){return this.count}};
osg.DrawElements.create=function(a,b){return new osg.DrawElements(a,b)};osg.Geometry=function(){osg.Node.call(this);this.primitives=[];this.attributes={}};
osg.Geometry.prototype=osg.objectInehrit(osg.Node.prototype,{getPrimitives:function(){return this.primitives},getAttributes:function(){return this.attributes},drawImplementation:function(a){for(var b,c=[],d=a.getLastProgramApplied().attributesCache,e=0,f=d.attributeKeys.length;e<f;e++){var g=d.attributeKeys[e];b=d[g];void 0!==this.attributes[g]&&(c.push(b),a.setVertexAttribArray(b,this.attributes[g],!1))}b=this.primitives;a.disableVertexAttribsExcept(c);c=0;for(d=b.length;c<d;++c)b[c].draw(a)}});
osg.Geometry.create=function(){return new osg.Geometry};osg.Transform={RELATIVE_RF:0,ABSOLUTE_RF:1};
osg.Camera=function(){void 0===osg.Camera.PRE_RENDER&&(osg.Camera.PRE_RENDER=0,osg.Camera.NESTED_RENDER=1,osg.Camera.POST_RENDER=2);osg.Node.call(this);this.viewport=void 0;this.setClearColor([0,0,0,1]);this.setClearDepth(1);this.setClearMask(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.setViewMatrix(osg.Matrix.makeIdentity());this.setProjectionMatrix(osg.Matrix.makeIdentity());this.renderOrder=osg.Camera.NESTED_RENDER;this.renderOrderNum=0;this.referenceFrame=osg.Transform.RELATIVE_RF};
osg.Camera.prototype=osg.objectInehrit(osg.Node.prototype,{setReferenceFrame:function(a){this.referenceFrame=a},getReferenceFrame:function(){return this.referenceFrame},setClearDepth:function(a){this.clearDepth=a},getClearDepth:function(){return this.clearDepth},setClearMask:function(a){this.clearMask=a},getClearMask:function(){return this.clearMask},setClearColor:function(a){this.clearColor=a},getClearColor:function(){return this.clearColor},setViewport:function(a){this.viewport=a;this.getOrCreateStateSet().setAttribute(a)},
getViewport:function(){return this.viewport},setViewMatrix:function(a){this.modelviewMatrix=a},setProjectionMatrix:function(a){this.projectionMatrix=a},getViewMatrix:function(){return this.modelviewMatrix},getProjectionMatrix:function(){return this.projectionMatrix},getRenderOrder:function(){return this.renderOrder},setRenderOrder:function(a,b){this.renderOrder=a;this.renderOrderNum=b},attachTexture:function(a,b,c){void 0===this.attachments&&(this.attachments={});this.attachments[a]={texture:b,level:c}}});
osg.NodeVisitor=function(){this.traversalMask=-1;this.nodeMaskOverride=0};
osg.NodeVisitor.prototype={setTraversalMask:function(a){this.traversalMask=a},getTraversalMask:function(){return this.traversalMask},validNodeMask:function(a){a=a.getNodeMask();return 0!==(this.traversalMask&(this.nodeMaskOverride|a))},apply:function(a){this.traverse(a)},traverse:function(a){void 0!==a.traverse&&a.traverse(this)},traverseNew:function(a){if(a.children)for(var b=0,c=a.children.length;b<c;b++){var d=a.children[b],e=d.getNodeMask();0!==(this.traversalMask&(this.nodeMaskOverride|e))&&
this.apply(d)}}};osg.NodeVisitor.create=function(){return new osg.NodeVisitor};osg.StateGraph=function(){this.depth=0;this.children={};this.children.keys=[];this.leafs=[];this.parent=this.stateset=void 0};
osg.StateGraph.prototype={clean:function(){for(var a=this.leafs.length=0,b=this.children.keys.length;a<b;a++)this.children[this.children.keys[a]].clean()},findOrInsert:function(a){var b;this.children[a.id]?b=this.children[a.id]:(b=new osg.StateGraph,b.parent=this,b.depth=this.depth+1,b.stateset=a,this.children[a.id]=b,this.children.keys.push(a.id));return b},moveStateGraph:function(a,b,c){var d;if(c!==b&&void 0!==c)if(void 0===b){d=[];do void 0!==c.stateset&&d.push(c.stateset),c=c.parent;while(c);
d.reverse();b=0;for(l=d.length;b<l;++b)a.pushStateSet(d[b])}else if(b.parent===c.parent)void 0!==b.stateset&&a.popStateSet(),void 0!==c.stateset&&a.pushStateSet(c.stateset);else{for(;b.depth>c.depth;)void 0!==b.stateset&&a.popStateSet(),b=b.parent;for(d=[];c.depth>b.depth;)void 0!==c.stateset&&d.push(c.stateset),c=c.parent;for(;b!==c;)void 0!==b.stateset&&a.popStateSet(),b=b.parent,void 0!==c.stateset&&d.push(c.stateset),c=c.parent;d.reverse();stackLength=d.length;for(b=0;b<stackLength;++b)a.pushStateSet(d[b])}}};
osg.RenderBin=function(a){this.leafs=[];this.stateGraph=a;this.positionedAttribute=[];this.renderStage=void 0;this.renderBin={};this.stateGraphList=[]};
osg.RenderBin.prototype={getStage:function(){return this.renderStage},addStateGraph:function(a){this.stateGraphList.push(a)},reset:function(){this.stateGraph=void 0;this.stateGraphList.length=0;this.renderBin={};this.positionedAttribute.length=0;this.leafs.length=0},applyPositionedAttribute:function(a,b){for(var c=0,d=b.length;c<d;c++){var e=b[c],f=e[1],e=e[0];a.setGlobalDefaultValue(f);f.applyPositionedUniform(e,a)}},drawImplementationNew:function(a,b){var c=b,d;for(d in this.renderBin)0>d&&(c=this.renderBin[d].drawImplementationNew(a,
c));c=this.drawLeafs(a,c);for(d in this.renderBin)0<=d&&(c=this.renderBin[d].drawImplementationNew(a,c));return c},drawLeafs:function(a,b){var c=this.stateGraphList,d,e,f;d=b;this.positionedAttribute&&this.applyPositionedAttribute(a,this.positionedAttribute);for(var g=0,h=c.length;g<h;g++)for(var k=c[g],m=0,p=k.leafs.length;m<p;m++){var n=k.leafs[m],q=!1;void 0!==d?(d=d.parent,e=d.parent,f=n.parent,e!==f.parent?(f.moveStateGraph(a,e,f.parent),a.pushStateSet(f.stateset),q=!0):f!==d&&(a.pushStateSet(f.stateset),
q=!0)):(n.parent.moveStateGraph(a,void 0,n.parent.parent),a.pushStateSet(n.parent.stateset),q=!0);!0===q&&a.apply();d=a.getLastProgramApplied();e=d.uniformsCache[a.modelViewMatrix.name];f=d.uniformsCache[a.projectionMatrix.name];d=d.uniformsCache[a.normalMatrix.name];void 0!==e&&null!==e&&-1!==e&&(a.modelViewMatrix.set(n.modelview),a.modelViewMatrix.apply(e));void 0!==f&&null!==f&&-1!=f&&(a.projectionMatrix.set(n.projection),a.projectionMatrix.apply(f));void 0!==d&&null!==d&&-1!==d&&(e=osg.Matrix.copy(n.modelview),
osg.Matrix.setTrans(e,0,0,0),osg.Matrix.inverse(e,e),osg.Matrix.transpose(e,e),a.normalMatrix.set(e),a.normalMatrix.apply(d));n.geometry.drawImplementation(a);!0===q&&(a.popGeneratedProgram(),a.popStateSet());d=n}return d},drawImplementation:function(a,b){var c=this.leafs,d,e,f,g;d=b;this.positionedAttribute&&this.applyPositionedAttribute(a,this.positionedAttribute);for(var h=0,k=this.leafs.length;h<k;h++){g=c[h];var m=!1;void 0!==d?(d=d.parent,e=d.parent,f=g.parent,e!==f.parent?(f.moveStateGraph(a,
e,f.parent),a.pushStateSet(f.stateset),m=!0):f!==d&&(a.pushStateSet(f.stateset),m=!0)):(g.parent.moveStateGraph(a,void 0,g.parent.parent),a.pushStateSet(g.parent.stateset),m=!0);!0===m&&a.apply();d=a.getLastProgramApplied();e=d.uniformsCache[a.modelViewMatrix.name];f=d.uniformsCache[a.projectionMatrix.name];d=d.uniformsCache[a.normalMatrix.name];void 0!==e&&null!==e&&-1!==e&&(a.modelViewMatrix.set(g.modelview),a.modelViewMatrix.apply(e));void 0!==f&&null!==f&&-1!=f&&(a.projectionMatrix.set(g.projection),
a.projectionMatrix.apply(f));void 0!==d&&null!==d&&-1!==d&&(e=osg.Matrix.copy(g.modelview),osg.Matrix.setTrans(e,0,0,0),osg.Matrix.inverse(e,e),osg.Matrix.transpose(e,e),a.normalMatrix.set(e),a.normalMatrix.apply(d));g.geometry.drawImplementation(a);!0===m&&(a.popGeneratedProgram(),a.popStateSet());d=g}return d}};
osg.RenderStage=function(){osg.RenderBin.call(this);this.positionedAttribute=[];this.clearDepth=1;this.clearColor=[0,0,0,1];this.clearMask=gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT;this.viewport=this.camera=void 0;this.preRenderList=[];this.postRenderList=[];this.renderStage=this};
osg.RenderStage.prototype=osg.objectInehrit(osg.RenderBin.prototype,{reset:function(){this.superObject.reset.call(this);this.preRenderList.length=0;this.postRenderList.length=0},setClearDepth:function(a){this.clearDepth=a},getClearDepth:function(){return this.clearDepth},setClearColor:function(a){this.clearColor=a},getClearColor:function(){return this.clearColor},setClearMask:function(a){this.clearMask=a},getClearMask:function(){return this.clearMask},setViewport:function(a){this.viewport=a},getViewport:function(){return this.viewport},
setCamera:function(a){this.camera=a},addPreRenderStage:function(a,b){for(var c=0,d=this.preRenderList.length;c<d&&!(b<this.preRenderList[c].order);c++);c<this.preRenderList.length?this.preRenderList=this.preRenderList.splice(c,0,{order:b,renderStage:a}):this.preRenderList.push({order:b,renderStage:a})},addPostRenderStage:function(a,b){for(var c=0,d=this.postRenderList.length;c<d&&!(b<this.postRenderList[c].order);c++);c<this.postRenderList.length?this.postRenderList=this.postRenderList.splice(c,0,
{order:b,renderStage:a}):this.postRenderList.push({order:b,renderStage:a})},drawPreRenderStages:function(a,b){for(var c=b,d=0,e=this.preRenderList.length;d<e;++d)c=this.preRenderList[d].renderStage.draw(a,c);return c},draw:function(a,b){var c=this.drawPreRenderStages(a,b),c=this.drawImplementation(a,c);return c=this.drawPostRenderStages(a,c)},drawPostRenderStages:function(a,b){for(var c=b,d=0,e=this.postRenderList.length;d<e;++d)c=this.postRenderList[d].renderStage.draw(a,c);return c},applyCamera:function(a){if(void 0===
this.camera)gl.bindFramebuffer(gl.FRAMEBUFFER,null);else{var b=this.camera.frameBufferObject;if(void 0===this.camera.frameBufferObject&&(b=new osg.FrameBufferObject,this.camera.frameBufferObject=b,void 0!==this.camera.attachments))for(var c in this.camera.attachments)b.setAttachment({attachment:c,texture:this.camera.attachments[c].texture,level:0});b.apply(a)}},drawImplementation:function(a,b){if(!0===osg.reportErrorGL){var c;c=gl.getError();osg.checkError(c)}this.applyCamera(a);void 0===this.viewport&&
osg.log("RenderStage does not have a valid viewport");a.applyAttribute(this.viewport);this.clearMask&gl.COLOR_BUFFER_BIT&&gl.clearColor(this.clearColor[0],this.clearColor[1],this.clearColor[2],this.clearColor[3]);this.clearMask&gl.DEPTH_BUFFER_BIT&&gl.clearDepth(this.clearDepth);gl.clear(this.clearMask);this.positionedAttribute&&this.applyPositionedAttribute(a,this.positionedAttribute);var d=this.superObject.drawImplementationNew.call(this,a,b);!0===osg.reportErrorGL&&(c=gl.getError(),osg.checkError(c));
return d}});osg.FrameStamp=function(){var a=0,b=0,c=0;this.setReferenceTime=function(a){b=a};this.setSimulationTime=function(a){c=a};this.getReferenceTime=function(){return b};this.getSimulationTime=function(){return c};this.setFrameNumber=function(b){a=b};this.getFrameNumber=function(){return a}};osg.UpdateVisitor=function(){osg.NodeVisitor.call(this);var a=new osg.FrameStamp;this.getFrameStamp=function(){return a};this.setFrameStamp=function(b){a=b}};
osg.UpdateVisitor.prototype=osg.objectInehrit(osg.NodeVisitor.prototype,{apply:function(a){if(void 0!==a.getUpdateCallback){var b=a.getUpdateCallback();if(void 0!==b){b.update(a,this);return}}a.traverse&&this.traverse(a)}});
osg.CullVisitor=function(){osg.NodeVisitor.call(this);this.modelviewMatrixStack=[osg.Matrix.makeIdentity()];this.projectionMatrixStack=[osg.Matrix.makeIdentity()];this.stateGraph=new osg.StateGraph;this.stateGraph.stateset=new osg.StateSet;this.currentStateGraph=this.stateGraph;this.renderBin=new osg.RenderBin(this.stateGraph)};
osg.CullVisitor.prototype=osg.objectInehrit(osg.NodeVisitor.prototype,{reset:function(){this.modelviewMatrixStack.length=1;this.projectionMatrixStack.length=1;this.stateGraph=new osg.StateGraph;this.stateGraph.stateset=new osg.StateSet;this.currentStateGraph=this.stateGraph;this.renderBin=new osg.RenderBin(this.stateGraph)},addPositionedAttribute:function(a){for(var b=this.stateGraph;void 0!==b.parent;)b=b.parent;this.renderBin.positionedAttribute.push([this.modelviewMatrixStack[this.modelviewMatrixStack.length-
1],a])},pushStateSet:function(a){this.currentStateGraph=this.currentStateGraph.findOrInsert(a)},popStateSet:function(){this.currentStateGraph=this.currentStateGraph.parent},pushModelviewMatrix:function(a){var b;b=osg.Matrix.copy(this.modelviewMatrixStack[this.modelviewMatrixStack.length-1]);a=osg.Matrix.mult(a,b);this.modelviewMatrixStack.push(a)},popModelviewMatrix:function(){this.modelviewMatrixStack.pop()},pushProjectionMatrixOld:function(a){var b;b=osg.Matrix.copy(this.projectionMatrixStack[this.projectionMatrixStack.length-
1]);a=osg.Matrix.mult(a,b);this.projectionMatrixStack.push(a)},pushProjectionMatrix:function(a){this.projectionMatrixStack.push(a)},popProjectionMatrix:function(){this.projectionMatrixStack.pop()},apply:function(a){a.getMatrix?this.pushModelviewMatrix(a.getMatrix()):a.getViewMatrix&&this.pushModelviewMatrix(a.getViewMatrix());if(a.getProjectionMatrix){var b=this.projectionMatrixStack[this.projectionMatrixStack.length-1];this.pushProjectionMatrix(osg.Matrix.mult(a.getProjectionMatrix(),b))}a.stateset&&
this.pushStateSet(a.stateset);a.light&&this.addPositionedAttribute(a.light);a.drawImplementation&&this.renderBin.leafs.push({parent:this.currentStateGraph,modelview:this.modelviewMatrixStack[this.modelviewMatrixStack.length-1],projection:this.projectionMatrixStack[this.projectionMatrixStack.length-1],geometry:a});a.traverse&&this.traverse(a);a.stateset&&this.popStateSet();(a.getMatrix||void 0!==a.getViewMatrix)&&this.popModelviewMatrix();void 0!==a.getProjectionMatrix&&this.popProjectionMatrix()}});
osg.CullVisitorNew=function(){osg.NodeVisitor.call(this);this.modelviewMatrixStack=[osg.Matrix.makeIdentity()];this.projectionMatrixStack=[osg.Matrix.makeIdentity()];this.viewportStack=[];this.rootRenderStage=this.currentRenderStage=this.currentRenderBin=this.currentStateGraph=this.rootStateGraph=void 0};
osg.CullVisitorNew.prototype=osg.objectInehrit(osg.NodeVisitor.prototype,{setStateGraph:function(a){this.currentStateGraph=this.rootStateGraph=a},setRenderStage:function(a){this.currentRenderBin=this.rootRenderStage=a},reset:function(){this.modelviewMatrixStack.length=1;this.projectionMatrixStack.length=1},getCurrentRenderBin:function(){return this.currentRenderBin},setCurrentRenderBin:function(a){this.currentRenderBin=a},addPositionedAttribute:function(a){var b=this.modelviewMatrixStack[this.modelviewMatrixStack.length-
1];this.currentRenderBin.getStage().positionedAttribute.push([b,a])},pushStateSet:function(a){this.currentStateGraph=this.currentStateGraph.findOrInsert(a)},popStateSet:function(){this.currentStateGraph=this.currentStateGraph.parent},getViewport:function(){return 0===this.viewportStack.length?void 0:this.viewportStack[this.viewportStack.length-1]},pushViewport:function(a){this.viewportStack.push(a)},popViewport:function(){this.viewportStack.pop()},pushModelviewMatrix:function(a){this.modelviewMatrixStack.push(a)},
popModelviewMatrix:function(){this.modelviewMatrixStack.pop()},pushProjectionMatrix:function(a){this.projectionMatrixStack.push(a)},popProjectionMatrix:function(){this.projectionMatrixStack.pop()},applyCamera:function(a){a.stateset&&this.pushStateSet(a.stateset);a.light&&this.addPositionedAttribute(a.light);var b,c;a.getReferenceFrame()===osg.Transform.RELATIVE_RF?(b=this.projectionMatrixStack[this.projectionMatrixStack.length-1],c=osg.Matrix.mult(a.getProjectionMatrix(),b),this.pushProjectionMatrix(c),
b=this.modelviewMatrixStack[this.modelviewMatrixStack.length-1],b=osg.Matrix.mult(a.getViewMatrix(),b)):(b=osg.Matrix.copy(a.getViewMatrix()),c=osg.Matrix.copy(a.getProjectionMatrix()),this.pushProjectionMatrix(c));this.pushModelviewMatrix(b);a.getViewport()&&this.pushViewport(a.getViewport());a.getRenderOrder()===osg.Camera.NESTED_RENDER?a.traverse&&this.traverse(a):(c=this.getCurrentRenderBin().getStage(),b=new osg.RenderStage,b.setCamera(a),b.setClearDepth(a.getClearDepth()),b.setClearColor(a.getClearColor()),
b.setClearMask(a.getClearMask()),c=void 0===a.getViewport()?c.getViewport():a.getViewport(),b.setViewport(c),c=this.getCurrentRenderBin(),this.setCurrentRenderBin(b),a.traverse&&a.traverse(this),this.setCurrentRenderBin(c),a.getRenderOrder()===osg.Camera.PRE_RENDER?this.getCurrentRenderBin().getStage().addPreRenderStage(b,a.renderOrderNum):this.getCurrentRenderBin().getStage().addPostRenderStage(b,a.renderOrderNum));this.popModelviewMatrix();this.popProjectionMatrix();a.getViewport()&&this.popViewport();
a.stateset&&this.popStateSet()},apply:function(a){var b;a.getProjectionMatrix&&a.getViewMatrix?this.applyCamera(a):(a.getMatrix?(b=this.modelviewMatrixStack[this.modelviewMatrixStack.length-1],b=osg.Matrix.mult(a.getMatrix(),b),this.pushModelviewMatrix(b)):a.getViewMatrix&&(b=this.modelviewMatrixStack[this.modelviewMatrixStack.length-1],b=osg.Matrix.mult(a.getViewMatrix(),b),this.pushModelviewMatrix(b)),a.getProjectionMatrix&&(b=this.projectionMatrixStack[this.projectionMatrixStack.length-1],b=osg.Matrix.mult(a.getProjectionMatrix(),
b),this.pushProjectionMatrix(b)),a.stateset&&this.pushStateSet(a.stateset),a.light&&this.addPositionedAttribute(a.light),a.drawImplementation&&(b=this.currentStateGraph.leafs,0===b.length&&this.currentRenderBin.addStateGraph(this.currentStateGraph),b.push({parent:this.currentStateGraph,modelview:this.modelviewMatrixStack[this.modelviewMatrixStack.length-1],projection:this.projectionMatrixStack[this.projectionMatrixStack.length-1],geometry:a})),a.traverse&&this.traverse(a),a.stateset&&this.popStateSet(),
(a.getMatrix||void 0!==a.getViewMatrix)&&this.popModelviewMatrix(),void 0!==a.getProjectionMatrix&&this.popProjectionMatrix())}});
osg.ParseSceneGraph=function(a){var b;if(a.primitives){b=osg.Geometry.create();jQuery.extend(b,a);a=b;for(var c in a.primitives)if(b=a.primitives[c].mode,a.primitives[c].indices){var d=a.primitives[c].indices,d=osg.BufferArray.create(gl[d.type],d.elements,d.itemSize);b=b?gl[b]:gl.TRIANGLES;a.primitives[c]=osg.DrawElements.create(b,d)}else{b=gl[b];var d=a.primitives[c].first,e=a.primitives[c].count;65535<e&&(e=32740);a.primitives[c]=new osg.DrawArrays(b,d,e)}}a.attributes&&jQuery.each(a.attributes,
function(b,c){var d=a.attributes[b];a.attributes[b]=osg.BufferArray.create(gl[d.type],d.elements,d.itemSize)});if(a.stateset){c=new osg.StateSet;if(a.stateset.textures)for(b=a.stateset.textures,d=0,e=b.length;d<e;d++)if(void 0!==b[d]){b[d].file||void 0!==console&&console.log("no 'file' field for texture "+b[d]);var f=osg.Texture.create(b[d].file);c.setTexture(d,f);c.addUniform(osg.Uniform.createInt1(d,"Texture"+d))}a.stateset.material&&(b=a.stateset.material,d=osg.Material.create(),jQuery.extend(d,
b),c.setAttribute(d));a.stateset=c}a.matrix&&(b=new osg.MatrixTransform,jQuery.extend(b,a),b.setMatrix(osg.Matrix.copy(a.matrix)),a=b);a.projection&&(b=new osg.Projection,jQuery.extend(b,a),b.setProjectionMatrix(osg.Matrix.copy(a.projection)),a=b);if(a.children)for(b=new osg.Node,jQuery.extend(b,a),a=b,c=0,b=a.children.length;c<b;c++)a.children[c]=osg.ParseSceneGraph(a.children[c]);void 0===a.accept&&(b=new osg.Node,jQuery.extend(b,a),a=b);return a};osg.View=function(){osg.Camera.call(this)};
osg.View.prototype=osg.objectInehrit(osg.Camera.prototype,{computeIntersections:function(a,b,c){void 0===c&&(c=-1);var d=new osgUtil.IntersectVisitor;d.setTraversalMask(c);d.addLineSegment([a,b,0],[a,b,1]);d.apply(this);return d.hits}});
osg.createTexuredQuad=function(a,b,c,d,e,f,g,h,k,m,p,n,q){void 0===n&&void 0===q&&(n=m,q=p,p=m=0);var u=new osg.Geometry,r=[];r[0]=a+g;r[1]=b+h;r[2]=c+k;r[3]=a;r[4]=b;r[5]=c;r[6]=a+d;r[7]=b+e;r[8]=c+f;r[9]=a+d+g;r[10]=b+e+h;r[11]=c+f+k;void 0===n&&(n=1);void 0===q&&(q=1);a=[];a[0]=m;a[1]=q;a[2]=m;a[3]=p;a[4]=n;a[5]=p;a[6]=n;a[7]=q;d=osg.Vec3.cross([d,e,f],[g,h,k]);e=[];e[0]=d[0];e[1]=d[1];e[2]=d[2];e[3]=d[0];e[4]=d[1];e[5]=d[2];e[6]=d[0];e[7]=d[1];e[8]=d[2];e[9]=d[0];e[10]=d[1];e[11]=d[2];u.getAttributes().Vertex=
osg.BufferArray.create(gl.ARRAY_BUFFER,r,3);u.getAttributes().Normal=osg.BufferArray.create(gl.ARRAY_BUFFER,e,3);u.getAttributes().TexCoord0=osg.BufferArray.create(gl.ARRAY_BUFFER,a,2);r=new osg.DrawElements(gl.TRIANGLES,osg.BufferArray.create(gl.ELEMENT_ARRAY_BUFFER,[0,1,2,0,2,3],1));u.getPrimitives().push(r);return u};osg.createTexturedQuad=osg.createTexuredQuad;
